steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/k8s-experiment-245209/flask-docker", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/k8s-experiment-245209/flask-docker"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - config
    - list
    - account
    - --format "value(core.account)"
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - flask-web-server
  - flask=gcr.io/k8s-experiment-245209/flask-docker:latest
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=terraform-cluster-2'